### ISSUE TITLE
Erro no envio de pdf via web service

### ISSUE THREAD

**Issue by josalm** [saphety-developers/api-notebooks#1]
Boa tarde
Ao fazer o pedido obtenho o seguinte erro.
`
"Code":"INVALID_ENUM","Field":"CurrencyCode","Values":["USD"] 
`
Segundo a documentação este formato está correto.
Segue o body do pedido
`{
  "IntlVatCode": "PT203065760",
  "DocumentType": "Invoice",
  "DocumentDate": "2023-07-31T15:42:04.0000000Z",
  "DocumentNumber": "FRG100001",
  "ReceiverIntlVatCode": "PT542263718",
  "ReceiverName": "Rui Esteves ",
  "DocumentTotal": 7156.36,
  "CurrencyCode": "USD",
  "SerializedInput": "PDF Base 64"
  "ContentType": "application/pdf"
}`
Conseguem ajudar?

**Comment by saphety-developers** [comment]
De momento só é suportado "EUR" como moeda.

**Comment by saphety-developers** [comment]
O nif indicado não é válido. Pode ferificar aqui: [https://www.nif.pt/?q=240732287](https://www.nif.pt/?q=240732287)
