### ISSUE TITLE
Authorize not in the valid date range

### ISSUE THREAD

**Issue by josalm** [saphety-developers/api-notebooks#3]
Boa tarde,
Estou a efetuar pedidos via serviço Saphety SIN e está a retornar este erro. 
Podem indicar a causa provável do mesmo?

Cumprimentos

**Comment by saphety-developers** [comment]
Boa tarde,

De modo a ser mais facil ajudar é possivel colocar aqui o endpoint invocado e a resposta dada pelo servidor incluindo os headers?

Obrigado

**Comment by josalm** [comment]
O problema foi ultrapassado. Vou fechar o issue.
Obrigado
